# Generated by Django 5.1.6 on 2025-03-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderrBackend_app', '0003_alter_offer_image_alter_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='CoderrBackend_app.offerdetail'),
        ),
    ]
